version: '3.8'

services:
  echo-api:
    build:
      context: .
      dockerfile: dockerfile
    container_name: echo-api
    ports:
      - "127.0.0.1:3200:3200"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
